export const Questions = [
  {
    prompt: "Which layer of the OSI model is responsible for logical addressing and routing?",
    optionA: "Application Layer",
    optionB: "Transport Layer",
    optionC: "Network Layer",
    optionD: "Data Link Layer",
    answer: "optionC",
  },
  {
    prompt: "Which protocol is used to find the MAC address of a device given its IP address?",
    optionA: "DNS",
    optionB: "ARP",
    optionC: "ICMP",
    optionD: "DHCP",
    answer: "optionB",
  },
  {
    prompt: "Which of the following protocols uses a three-way handshake to establish a connection?",
    optionA: "HTTP",
    optionB: "TCP",
    optionC: "UDP",
    optionD: "ICMP",
    answer: "optionB",
  },
  {
    prompt: "Which layer of the OSI model is responsible for end-to-end delivery and error control?",
    optionA: "Transport Layer",
    optionB: "Session Layer",
    optionC: "Data Link Layer",
    optionD: "Application Layer",
    answer: "optionA",
  },
  {
    prompt: "Which device operates primarily at Layer 2 (Data Link Layer) of the OSI model?",
    optionA: "Router",
    optionB: "Switch",
    optionC: "Hub",
    optionD: "Repeater",
    answer: "optionB",
  },
  {
    prompt: "What does DNS stand for?",
    optionA: "Dynamic Name Service",
    optionB: "Domain Name Service",
    optionC: "Domain Name System",
    optionD: "Data Network System",
    answer: "optionC",
  },
  {
    prompt: "Which protocol is used to send error and control messages, such as 'Destination Unreachable'?",
    optionA: "TCP",
    optionB: "UDP",
    optionC: "ICMP",
    optionD: "HTTP",
    answer: "optionC",
  },
  {
    prompt: "Which of the following best describes the function of a router?",
    optionA: "Connects devices within the same LAN",
    optionB: "Repeats signals to extend network range",
    optionC: "Routes packets between different networks",
    optionD: "Provides wireless connectivity",
    answer: "optionC",
  },
];
